baseURL: https://efa44.org/
languageCode: fr-fr
title: EFA44
theme: efa44
buildFuture: true

params:
  description: Enfance & Familles d'Adoption de Loire-Atlantique
  tagline: Accompagner les familles adoptives depuis 1958
  logo: /images/efa44-logo-small.svg
  logoAlt: EFA 44 - Enfance & Familles d'Adoption Loire-Atlantique
  favicon: /images/favicon.jpg
  contact:
    email: contact@efa44.org
    address:
      name: Pôle associatif Désiré Colombe
      street: 8 rue Arsène Leloup
      city: 44100 Nantes
  social:
    federation:
      name: Fédération EFA
      url: https://www.adoptionefa.org/
