fr:
  languageName: Français
  weight: 1
  ### copyright (le markdown peut être utilisé) ###
  copyright: "Copyright &copy; {{< current_year >}} EFA44. Tous droits réservés. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) pour Hugo par [CNCF](https://www.cncf.io)."
  title: "EFA 44"
  params:
    description: "Depuis 1958, Enfance & Familles d'Adoption de Loire-Atlantique, plus couramment appelée EFA 44, accompagne les familles adoptives, les candidats à l'adoption et les adoptés devenus adultes dans le respect de leur parcours et de leurs besoins. Association départementale loi 1901, EFA 44 rassemble près de 300 adhérents, avec un Conseil d’Administration et un bureau composé de parents adoptifs et d’adoptés majeurs, tous bénévoles, qui partagent avec conviction leur expérience et leurs connaissances."
    ### accessibilité ###
    # accessibility:
    #   skip_text: "Aller au contenu"
    #   help_text: "Déclaration d’accessibilité"
    #   help_url: "/page-exemple/"
    ### appels à l’action ###
    main_cta:
      text: "Adhérer"
      link: "/pages/nous-rejoindre/"
    footer_cta:
      text: "Adhérer"
      link: "/pages/nous-rejoindre/"
    github_edit: "Modifier cette page sur GitHub"
  ### exemple de menu avec sous-pages ###
  menu:
    main:
    - identifier: "about"
      name: "À propos de nous"
      weight: 1
      post: "En savoir plus sur notre mission, notre histoire et nos valeurs."
    - identifier: "about-efa44"
      name: "Le bureau"
      url: "/pages/bureau"
      weight: 1
      post: "En savoir plus sur notre mission, notre histoire et nos valeurs."
      parent: "about"
    - identifier: "about-efa"
      name: "À propos de la férération EFA"
      url: "/pages/federation"
      weight: 2
      post: "En savoir plus sur la maison mère EFA, ses actions et son impact."
      parent: "about"
    - identifier: "situation"
      name: "À propos de vous"
      weight: 2
      post: "Trouvez des réponses adaptées à votre situation spécifique."
    - identifier: "child-1"
      name: "Adopté ?"
      url: "/pages/adoptes"
      weight: 1
      post: "Découvrez des ressources et des témoignages pour les adoptés."
      parent: "situation"
    - identifier: "child-2"
      name: "Candidats à l'adoption"
      url: "/pages/postulants"
      weight: 2
      post: "Informations et conseils pour les candidats à l'adoption."
      parent: "situation"
    - identifier: "child-3"
      name: "Famille adoptive"
      url: "/pages/familles"
      weight: 3
      post: "Soutien et accompagnement pour les familles adoptives."
      parent: "situation"
    - identifier: "events"
      name: "Évènements"
      url: "/events/"
      weight: 4
      post: "Lisez nos articles et actualités sur l'adoption et la parentalité."