######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/efa44-logo-small.svg"
logo_on_black: "/img/efa44-logo.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/efa44-logo.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/EnfanceetFamillesAdoption44"
  flickr: ""
  github: ""
  instagram: "https://www.instagram.com/efa.44loireatlantique/"
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
